# What is PyTorch?
- Popular research deep learning framework.
- Write fast deep learning code in Python (able to run on a GPU/many GPUs)
- Able to access many pre-built deep learning models (Torch Hub/torchvision.models)
- Whole stack: preprocesss data, model data, deploy modle in your application/cloud

Importing Pytorch

In [3]:
import torch
torch.__version__

'2.5.1+cu124'

## What is a Tensor
Tensors are fundamental building block of machine learning.
Their job is to represent data in a numerical way.

A `torch.Tensor` is a multi-dimensional matrix containing elements of a single data type.

Lets create a scalar.

### Scalar
A scalar is a single number, or a zero dimension vector.

In [31]:
# Scalr
scalar = torch.tensor(7)
scalar

tensor(7)

In [34]:
## Check on the dimension of a tensor using ndim attribute
scalar.ndim

0

`item()`: Method to retrieve a number from the tensor.

In [42]:
# Get the Python number within a tensor (only works with 1-element tensors)
scalar.item()

7

### Vector
Vector is a single dimension tensor that can contain many numbers.

In [53]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [60]:
vector.ndim

1

### Shape
Shape attribute tells you how the elements inside them are arranged.

In [66]:
vector.shape

torch.Size([2])

In [73]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [76]:
MATRIX.ndim

2

In [79]:
MATRIX.shape

torch.Size([2, 2])

In [82]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [85]:
TENSOR.ndim

3

In [88]:
TENSOR.shape

torch.Size([1, 3, 3])

In [102]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [107]:
TENSOR[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [117]:
TENSOR[0][0]

tensor([1, 2, 3])

In [122]:
TENSOR[0][2]

tensor([2, 4, 5])

## Random Tensors
Tensors represent some form of data.
Machine learning models susch as neural networks manipulate and seek patterns within tensors. But when building machine learning models with PyTorch, it's rare you'll create tensors by hand. Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works throught data to better represent it.

In essence:

```
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...
````

Lets create a tensor of random numbers.

We can do so using `torch.rand()` and passing in the `size` parameter.

In [94]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7698, 0.8748, 0.3200, 0.9173],
         [0.0349, 0.8915, 0.4879, 0.3367],
         [0.0082, 0.0475, 0.0986, 0.5182]]),
 torch.float32)

The flexibility of `torch.rand()` is that we can adjust the `size` to be whatever we want.

For example, say you wanted  a random tensor in the scommon image shape of `[224, 224, 3]` `([height, width, color_channels])`.

In [218]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 5, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 5, 3]), 3)

In [221]:
random_image_size_tensor

tensor([[[0.1611, 0.4704, 0.4695],
         [0.6632, 0.6139, 0.9958],
         [0.4580, 0.0316, 0.2574],
         [0.7860, 0.6027, 0.7729],
         [0.2386, 0.0367, 0.5478]],

        [[0.8969, 0.6494, 0.5929],
         [0.3647, 0.7664, 0.3178],
         [0.3145, 0.2281, 0.7609],
         [0.4816, 0.7887, 0.8978],
         [0.7446, 0.4158, 0.1385]],

        [[0.9762, 0.5909, 0.1351],
         [0.5448, 0.5314, 0.8870],
         [0.9934, 0.8699, 0.7640],
         [0.7952, 0.8220, 0.8724],
         [0.7941, 0.1118, 0.4573]],

        ...,

        [[0.1838, 0.3318, 0.6432],
         [0.3355, 0.2979, 0.0470],
         [0.0516, 0.6750, 0.9755],
         [0.4237, 0.3471, 0.0161],
         [0.5369, 0.4983, 0.9655]],

        [[0.7195, 0.0725, 0.7615],
         [0.8931, 0.7393, 0.8636],
         [0.3742, 0.5550, 0.6185],
         [0.8954, 0.3570, 0.0303],
         [0.6586, 0.7897, 0.5219]],

        [[0.7488, 0.1396, 0.6514],
         [0.0350, 0.3677, 0.6284],
         [0.6115, 0.6368, 0.274

In [224]:
random_image_size_tensor[0]

tensor([[0.1611, 0.4704, 0.4695],
        [0.6632, 0.6139, 0.9958],
        [0.4580, 0.0316, 0.2574],
        [0.7860, 0.6027, 0.7729],
        [0.2386, 0.0367, 0.5478]])

## Zeros and Ones
Sometimes you;ll just want to fill tensors with zeros and ones.
This happens a lot with masking (like masking some oaf the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with `torch.zeros()`

Again, the `size` parameter comes to play.

In [230]:
## Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

We can do the same to create a tensor of all ones excep using `torch.ones()` instead.

In [236]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Create a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

Where:
- `start` = start of range (eg., 0)
- `end` = end of range (eg., 10)
- `step` = how many steps in between each value (eg., 1)

Note! In Python, you can use `range()` to create a range. However in PyTorch, `torch.range()` is deprecated and may show an aerror in the future.

In [252]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with ther same shape as another tensor. For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use `torch.zeros_like(input)` or `torch.ones_like(input=zero_to_ten)` which return a tensor filled with zeros or ones in the same shape as the `input` respecively.

In [258]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Precision in Computing
Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number. 

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute but sacrifice some performance on evaluation methorics like accuracy (faster to compute but less accurate).

In [264]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0,],
                                dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                                device=None, # defaults to None, which uses the default tensor type
                                requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [269]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=torch.float16) # torch.float16) # torch.half would alsowork
float_16_tensor.dtype

torch.float16

## Getting Information from Tensors
- `shape`: what shape is the tensor? (some operations require specific shape rules)
- `dtype`: what datatype are the 