# What is PyTorch?
- Popular research deep learning framework.
- Write fast deep learning code in Python (able to run on a GPU/many GPUs)
- Able to access many pre-built deep learning models (Torch Hub/torchvision.models)
- Whole stack: preprocesss data, model data, deploy modle in your application/cloud

Importing Pytorch

In [3]:
import torch
torch.__version__

'2.4.1+cu121'

## What is a Tensor
Tensors are fundamental building block of machine learning.
Their job is to represent data in a numerical way.

A `torch.Tensor` is a multi-dimensional matrix containing elements of a single data type.

Lets create a scalar.

### Scalar
A scalar is a single number, or a zero dimension vector.

In [31]:
# Scalr
scalar = torch.tensor(7)
scalar

tensor(7)

In [34]:
## Check on the dimension of a tensor using ndim attribute
scalar.ndim

0

`item()`: Method to retrieve a number from the tensor.

In [42]:
# Get the Python number within a tensor (only works with 1-element tensors)
scalar.item()

7

### Vector
Vector is a single dimension tensor that can contain many numbers.

In [53]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [60]:
vector.ndim

1

### Shape
Shape attribute tells you how the elements inside them are arranged.

In [66]:
vector.shape

torch.Size([2])

In [73]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [76]:
MATRIX.ndim

2

In [79]:
MATRIX.shape

torch.Size([2, 2])

In [82]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [85]:
TENSOR.ndim

3

In [88]:
TENSOR.shape

torch.Size([1, 3, 3])

In [102]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [107]:
TENSOR[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [117]:
TENSOR[0][0]

tensor([1, 2, 3])

In [122]:
TENSOR[0][2]

tensor([2, 4, 5])

## Random Tensors
Tensors represent some form of data.
Machine learning models susch as neural networks manipulate and seek patterns within tensors. But when building machine learning models with PyTorch, it's rare you'll create tensors by hand. Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works throught data to better represent it.

In essence:

```
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...
````

Lets create a tensor of random numbers.

We can do so using `torch.rand()` and passing in the `size` parameter.

In [94]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7698, 0.8748, 0.3200, 0.9173],
         [0.0349, 0.8915, 0.4879, 0.3367],
         [0.0082, 0.0475, 0.0986, 0.5182]]),
 torch.float32)

The flexibility of `torch.rand()` is that we can adjust the `size` to be whatever we want.

For example, say you wanted  a random tensor in the scommon image shape of `[224, 224, 3]` `([height, width, color_channels])`.

In [218]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 5, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 5, 3]), 3)

In [221]:
random_image_size_tensor

tensor([[[0.1611, 0.4704, 0.4695],
         [0.6632, 0.6139, 0.9958],
         [0.4580, 0.0316, 0.2574],
         [0.7860, 0.6027, 0.7729],
         [0.2386, 0.0367, 0.5478]],

        [[0.8969, 0.6494, 0.5929],
         [0.3647, 0.7664, 0.3178],
         [0.3145, 0.2281, 0.7609],
         [0.4816, 0.7887, 0.8978],
         [0.7446, 0.4158, 0.1385]],

        [[0.9762, 0.5909, 0.1351],
         [0.5448, 0.5314, 0.8870],
         [0.9934, 0.8699, 0.7640],
         [0.7952, 0.8220, 0.8724],
         [0.7941, 0.1118, 0.4573]],

        ...,

        [[0.1838, 0.3318, 0.6432],
         [0.3355, 0.2979, 0.0470],
         [0.0516, 0.6750, 0.9755],
         [0.4237, 0.3471, 0.0161],
         [0.5369, 0.4983, 0.9655]],

        [[0.7195, 0.0725, 0.7615],
         [0.8931, 0.7393, 0.8636],
         [0.3742, 0.5550, 0.6185],
         [0.8954, 0.3570, 0.0303],
         [0.6586, 0.7897, 0.5219]],

        [[0.7488, 0.1396, 0.6514],
         [0.0350, 0.3677, 0.6284],
         [0.6115, 0.6368, 0.274

In [224]:
random_image_size_tensor[0]

tensor([[0.1611, 0.4704, 0.4695],
        [0.6632, 0.6139, 0.9958],
        [0.4580, 0.0316, 0.2574],
        [0.7860, 0.6027, 0.7729],
        [0.2386, 0.0367, 0.5478]])

## Zeros and Ones
Sometimes you;ll just want to fill tensors with zeros and ones.
This happens a lot with masking (like masking some oaf the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with `torch.zeros()`

Again, the `size` parameter comes to play.

In [230]:
## Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

We can do the same to create a tensor of all ones excep using `torch.ones()` instead.

In [236]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Create a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

Where:
- `start` = start of range (eg., 0)
- `end` = end of range (eg., 10)
- `step` = how many steps in between each value (eg., 1)

Note! In Python, you can use `range()` to create a range. However in PyTorch, `torch.range()` is deprecated and may show an aerror in the future.

In [252]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with ther same shape as another tensor. For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use `torch.zeros_like(input)` or `torch.ones_like(input=zero_to_ten)` which return a tensor filled with zeros or ones in the same shape as the `input` respecively.

In [258]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Precision in Computing
Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number. 

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute but sacrifice some performance on evaluation methorics like accuracy (faster to compute but less accurate).

In [264]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0,],
                                dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                                device=None, # defaults to None, which uses the default tensor type
                                requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [269]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=torch.float16) # torch.float16) # torch.half would alsowork
float_16_tensor.dtype

torch.float16

## Getting Information from Tensors
- `shape`: what shape is the tensor? (some operations require specific shape rules)
- `dtype`: what datatype are the elements within the tensor stored in?
- `device`: what device is the tensor stored on? (usually GPU or CPU)

In [16]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3726, 0.3611, 0.8922, 0.6085],
        [0.4945, 0.4295, 0.4961, 0.4770],
        [0.5786, 0.6301, 0.2932, 0.1206]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 3 Biggers in PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

# Manipulating tensors (tensors operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and perfoming a series of operations (could be 1,0000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication.

## Basic Operations
Let's strat with a few of the fundamental operations, addition (`+`), subtraction (`-`), multiplication (`*`).

In [35]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Notice how the tensor values didn't end up being `tensor([110, 120, 130])`, this is because the values inside the tensor don't change unless they're reassigned.

In [44]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [47]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [50]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch also has a bunch of built-in functions like `torch.mul()` (short for multiplication) and `torch.add()` to perform basic operations.

In [56]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [59]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

However, it's more common to use the operator symbols like `*` instead of `torch.mul()`

In [74]:
# Element-wise multiplication (each element multiples its equibalent, index 0 -> 0, 1 -> 1, 2 -> 2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [65]:
tensor

tensor([1, 2, 3])

# Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

Pytorch implements matrix multiplicatin functionality in the `torch.matmul()` method.

The main 2 rules for matrix multiplication to remember are:

1. The inner dimensions must match:
```
(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work
```
2. The resulting matrix has the shape of the outer dimensions:
```
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)
```
Note: "@" in Python is the symbol for matrix multiplication.


Lets create a tensor and perform element-wise multiplication and matrix multiplication on it.

In [85]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

The difference between element-wise multiplicaiton and matrix multiplication in the addition of values.

For our `tensor` varialbe with values `[1, 2, 3]`:

|Operation|Calculaltion|Code|
|---|---|---|
|Element-wise multiplication|`[1*1, 2*2, 3*3]`=`[1, 4, 5]`|`tensor * tensor`|
|Matrix multiplicatin|`[1*1, 2*2, 3*3]`=`[14]`|`torch.matmul(tensor)`|

In [185]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [188]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [198]:
# Can also use the "@" symbol for matrix multiplicaiton, through not recommended
tensor @ tensor

tensor(14)

In [205]:
tensor_A = torch.tensor([[1], [2], [3]])
tensor_A.shape

torch.Size([3, 1])

In [208]:
torch.matmul(tensor, tensor_A)

tensor([14])

In [221]:
torch.matmul(tensor_A, tensor_A.T)

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [224]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their inner dimensions match.

One of the ways to do thsi is with a `transpose` (swithc the dimensions of a given tensor).

You can perform transposes in PyTorch using either:
- `torch.transpose(input, dim0, dim1)`: where `input` is thedesired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
- `tensor.T`: where `tensor` is the desired tensor to trnaspose.

In [230]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [233]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [242]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

You can also use `torch.mm()` which is short for `torch.matmul()`

In [247]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

# torch.nn.Linear()
Neural networks are full of matrix multiplications and dot products.

The `torch.nn.Linear()` module, also known as a feed-forward layer or fully connected layer, implements a matrix multiplicatiin between an input `x` and weights matrix `A`.

$$
y = x\cdot A^{T}+b
$$

Where:
- `x`: is the input layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other).
- `A`: is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "`T`", that's because the weights matrix gets transposed).
- - Note: You might also often see `W` or another letter like `X` used to showcase the weights matrix.
- `b` is the bias term used to slightly offset the weights and inputs.
- `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like $y = mx + b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below to see what happens.

Do you notice anything to do with the shapes?

# since the linear layers starts with a random weights matrix, let's make it reproducible
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

## Reshaping, Stacking, Squeezing and Unsqueezing

|Method|One-line description|
|---|---|
|torch.reshape(input, shape)|Reshapes input to shap (if compatible), cna also sue torch.tensor.reshape()|
|Tensor.view(shape)|Returns a view of the original tensor.|
|torch.stack(tensors, dim=0)|Concatinates a sequence of tensros along a new dimension (dim), all tensors must be same size.|
|torch.squeeze(input)|Squeezes input to remove all the dimensions with value 1.|
|torch.unsqueeze(input, dim)|Returns input with a dimension value of 1 added at dim.|
|torch.permute(input, dims)|Returns a view of the original input with its dimensions permuted (rearranged to dims.|

Lets create a tensor

In [376]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Now let's add an extra dimension with `torch.reshape()`.

In [385]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

We can also change the view with `torch.view()`

In [407]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Remember though, changing the view of a tensor with `torch.view()` really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

In [411]:
# changing z changesx x
z[: 0] = 5
z, x

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), tensor([1., 2., 3., 4., 5., 6., 7.]))

If we wanted to stack our new tensor on top of itself 5 times, we could do so with `torch.stack()`.

In [421]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

We can use `torch.squeeze()` to remove all singel dimensions from a tensor.

In [427]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


You can use `torch.unsqueeze()` to add a dimension value to 1 at a specific index.

In [435]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


You can also rearrange the order of axes values with `torch.permutate(input, dims)`, where the `input` gets turned into a view with new `dims`.

In [441]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the x axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Getting PyTorch to run on the GPU
You can use a GPU to store data (tensors) and computing on data (performing operations on tensors).

To do so, you can use the `torch.cuda` package.

To test if PyTorch has access to a GPU using `torch.cuda.is_available()`.

In [1]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [4]:
!nvidia-smi

Fri Dec  6 19:40:48 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    Off |   00000000:01:00.0 Off |                  N/A |
|  0%   37C    P8             10W /  285W |     191MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----